name: Test AI App

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      FAL_KEY: ${{ secrets.FAL_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: set up python 
        uses: actions/setup-phython@v5
        with:
         python-version: "3.11"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Test merge
        run: python nightclub_ai.py

      - name: Upload nightclub image
        uses: actions/upload-artifact@v4
        with:
          name: nightclub-image
          path: nightclub_output.jpg
        
