name: Test AI App

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      FAL_KEY: ${{ secrets.FAL_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: upload nightclub image
        uses: actions/upload-python@v4
        with:
         name: nightclub_image
         path: nightclub_image.jpg
         
          python-version: "3.11"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Test merge
        run: python nightclub_ai.py

      
        
